name: CI/CD Pipeline for Soulpage Frontend and Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install Python Dependencies
        run: |
          cd backend
          # Ensure the system is updated
          sudo apt update

          # Install necessary packages
          sudo apt install -y python3 python3-pip python3-venv pkg-config libmysqlclient-dev

          # Create and activate a virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Upgrade pip in the virtual environment
          pip3 install --upgrade pip

          # Install project dependencies
          pip3 install -r requirements.txt

          # Set up environment variables
          cp .env.example .env
          echo '9km$(y_v+w_9cc^%z31e0g#7r8kp_6@(2i2ayqsb%rlxtoqic&' > .env

          # Run Django migrations
          python3 manage.py migrate

      - name: Deploy Frontend
        run: |
          sudo cp -r frontend/nextjs-app.service /etc/systemd/system/nextjs-app.service
          sudo systemctl daemon-reload
          sudo systemctl start nextjs-app.service
          sudo systemctl enable nextjs-app.service
          sudo systemctl status nextjs-app.service

      - name: Deploy Backend
        run: |
          sudo cp -r backend/django-app.service /etc/systemd/system/django-app.service
          sudo systemctl daemon-reload
          sudo systemctl start django-app.service
          sudo systemctl enable django-app.service
          sudo systemctl status django-app.service
